services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: soa
    ports:
      - 5444:5432
    volumes:
      - ./labworks-service/src/main/resources/sql/ddl-init.sql:/docker-entrypoint-initdb.d/1-ddl-init.sql
      - ./labworks-service/src/main/resources/sql/dml-init.sql:/docker-entrypoint-initdb.d/2-dml-init.sql
    restart: unless-stopped
    networks:
      - soa-network

  service-discovery:
    image: consul:1.15.4
    ports:
      - 8500:8500
    networks:
      - soa-network
    command: [ "agent", "-dev", "-client=0.0.0.0" ]

  labworks-service:
    build:
      context: .
      dockerfile: ./labworks-service/Dockerfile
    depends_on:
      - db
    ports:
      - 5269:5269 # https port
      - 5268:5268 # http port
    restart: unless-stopped
    networks:
      - soa-network

  labworks-rest-1:
    build:
      context: .
      dockerfile: ./labworks-rest/Dockerfile
    depends_on:
      - db
      - service-discovery
    ports:
      - 5169:5169 # https port
      - 5168:5168 # http port
    environment:
      - SPRING_CLOUD_CONSUL_DISCOVERY_INSTANCE-ID=labworks-rest-1
    restart: unless-stopped
    networks:
      - soa-network

  labworks-rest-2:
    build:
      context: .
      dockerfile: ./labworks-rest/Dockerfile
    depends_on:
      - db
      - service-discovery
    ports:
      - 5171:5169 # https port
      - 5170:5168 # http port
    environment:
      - SPRING_CLOUD_CONSUL_DISCOVERY_INSTANCE-ID=labworks-rest-2
    restart: unless-stopped
    networks:
      - soa-network

  bars-ejb:
    build:
      context: .
      dockerfile: ./bars-ejb/Dockerfile
    ports:
      - 9080:9080
      - 10990:10990 # mgmt
    restart: unless-stopped
    networks:
      - soa-network

  bars-service-1:
    build:
      context: .
      dockerfile: ./bars-service/Dockerfile
    depends_on:
      - bars-ejb
    ports:
      - 9677:9677 # https port
      - 9676:9676 # http port
    restart: unless-stopped
    networks:
      - soa-network

  bars-service-2:
    build:
      context: .
      dockerfile: ./bars-service/Dockerfile
    depends_on:
      - bars-ejb
    ports:
      - 9679:9677 # https port
      - 9678:9676 # http port
    restart: unless-stopped
    networks:
      - soa-network

  balancer:
    build:
      context: .
      dockerfile: ./balancer/Dockerfile
    ports:
      - 4444:4444
      - 8404:8404 # stats
    depends_on:
      - service-discovery
      - labworks-rest-1
      - labworks-rest-2
      - bars-service-1
      - bars-service-2
    restart: unless-stopped
    networks:
      - soa-network

  mule-esb:
    build:
      context: .
      dockerfile: ./mule-esb/Dockerfile
    ports:
      - 8081:8081
    depends_on:
      - labworks-service
    restart: unless-stopped
    networks:
      - soa-network

networks:
  soa-network:
    driver: bridge