HTTP/1.1 503 Service Unavailable
Connection: close
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: X-Requested-With, Authorization, Accept-Version, Content-MD5, CSRF-Token, Content-Type
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, PATCH, OPTIONS, HEAD
Access-Control-Allow-Origin: *
Cache-Control: no-cache
Content-Type: application/json

{
    "messages": ["Service is not available"]
}